name: radiobiom
channels:
  - defaults
dependencies:
  - python=3.10
  - timm
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - pytorch-cuda=11.8
  - pandas
  - pillow
  - scikit-learn
  - cudatoolkit=10.2
  - matplotlib