name: radiobiom
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - timm
  - pytorch==1.12.1
  - torchvision==0.13.1
  - pandas
  - pillow
  - scikit-learn
  - matplotlib